import { useState } from 'react';
import ModalShell from '../ui/ModalShell';
import Btn from '../ui/Btn';
import { VERSION, DEVELOPER } from '../../constants';

function ExportModal({ tables, relations, onClose }) {
  const [tab, setTab] = useState("mysql");
  const tabs = [{ key: "mysql", label: "MySQL", icon: "🐬" }, { key: "postgres", label: "PostgreSQL", icon: "🐘" }, { key: "laravel", label: "Laravel", icon: "🔶" }, { key: "prisma", label: "Prisma", icon: "△" }];
  const fmtType = (f, d) => { const s = f.size ? `(${f.size})` : ""; const map = { mysql: { int: `INT${s}`, bigint: `BIGINT${s}`, varchar: `VARCHAR${s || "(255)"}`, text: "TEXT", decimal: `DECIMAL${s || "(10,2)"}`, float: `FLOAT${s}`, date: "DATE", timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP", enum: `VARCHAR${s || "(50)"}`, boolean: "TINYINT(1)", json: "JSON", uuid: "CHAR(36)" }, postgres: { int: "INTEGER", bigint: "BIGINT", varchar: `VARCHAR${s || "(255)"}`, text: "TEXT", decimal: `NUMERIC${s || "(10,2)"}`, float: "REAL", date: "DATE", timestamp: "TIMESTAMPTZ DEFAULT NOW()", enum: `VARCHAR${s || "(50)"}`, boolean: "BOOLEAN", json: "JSONB", uuid: "UUID DEFAULT gen_random_uuid()" } }; return map[d]?.[f.type] || `VARCHAR${s || "(255)"}`; };
  const toPascal = s => s.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join("");
  const toCamel = s => { const p = toPascal(s); return p.charAt(0).toLowerCase() + p.slice(1); };
  const pType = { int: "Int", bigint: "BigInt", varchar: "String", text: "String", decimal: "Decimal", float: "Float", date: "DateTime", timestamp: "DateTime", enum: "String", boolean: "Boolean", json: "Json", uuid: "String" };
  const lM = { int: "integer", bigint: "bigInteger", varchar: "string", text: "text", decimal: "decimal", float: "float", date: "date", timestamp: "timestamp", enum: "string", boolean: "boolean", json: "json", uuid: "uuid" };
  const generate = () => {
    const hdr = `-- Generated by ERD Builder v${VERSION}\n-- ${new Date().toISOString()}\n-- Developer: ${DEVELOPER}\n-- Format: ${tab.toUpperCase()}\n\n`;
    if (tab === "mysql") { let sql = hdr; for (const t of tables) { sql += `CREATE TABLE \`${t.name}\` (\n`; const lines = t.fields.map(f => { let l = `  \`${f.name}\` ${fmtType(f, "mysql")}`; if (f.isPrimary || f.name === "id") l += " PRIMARY KEY AUTO_INCREMENT"; else if (!f.nullable) l += " NOT NULL"; return l; }); const fks = relations.filter(r => r.from === t.name).map(r => `  FOREIGN KEY (\`${r.fromField}\`) REFERENCES \`${r.to}\`(\`${r.toField}\`)`); sql += [...lines, ...fks].join(",\n") + "\n);\n\n"; } return sql; }
    if (tab === "postgres") { let sql = hdr; for (const t of tables) { sql += `CREATE TABLE "${t.name}" (\n`; const lines = t.fields.map(f => { let pt = fmtType(f, "postgres"); if ((f.isPrimary || f.name === "id") && (f.type === "int" || f.type === "bigint")) pt = f.type === "bigint" ? "BIGSERIAL" : "SERIAL"; let l = `  "${f.name}" ${pt}`; if (f.isPrimary || f.name === "id") l += " PRIMARY KEY"; else if (!f.nullable) l += " NOT NULL"; return l; }); const fks = relations.filter(r => r.from === t.name).map(r => `  CONSTRAINT "fk_${t.name}_${r.fromField}" FOREIGN KEY ("${r.fromField}") REFERENCES "${r.to}"("${r.toField}")`); sql += [...lines, ...fks].join(",\n") + "\n);\n\n"; t.fields.filter(f => f.isForeign).forEach(fk => { sql += `CREATE INDEX "idx_${t.name}_${fk.name}" ON "${t.name}" ("${fk.name}");\n`; }); sql += "\n"; } return sql; }
    if (tab === "laravel") { let c = `// Generated by ERD Builder v${VERSION} — Laravel\n// ${DEVELOPER}\n\n`; for (const t of tables) { c += `Schema::create('${t.name}', function (Blueprint $table) {\n`; for (const f of t.fields) { if (f.name === "id") { c += `    $table->id();\n`; continue; } if (f.name === "created_at" || f.name === "updated_at") continue; const m = lM[f.type] || "string"; c += `    $table->${m}('${f.name}'`; if (f.size && (f.type === "varchar" || f.type === "decimal")) { if (f.type === "decimal") { const p = f.size.split(","); c += `, ${p[0] || 10}, ${p[1] || 2}`; } else c += `, ${f.size}`; } c += `)`; if (f.isForeign) { const rel = relations.find(r => r.from === t.name && r.fromField === f.name); if (rel) c += `->constrained('${rel.to}')`; } if (f.nullable) c += `->nullable()`; c += `;\n`; } if (t.fields.some(f => f.name === "created_at")) c += `    $table->timestamps();\n`; c += `});\n\n`; } return c; }
    if (tab === "prisma") { let s = `// Generated by ERD Builder v${VERSION} — Prisma\n// ${DEVELOPER}\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`; for (const t of tables) { const mdl = toPascal(t.name); s += `model ${mdl} {\n`; for (const f of t.fields) { if (f.name === "id") { s += `  ${f.name.padEnd(14)}${(f.type === "uuid" ? "String" : "Int").padEnd(10)}@id ${f.type === "uuid" ? "@default(uuid())" : "@default(autoincrement())"}\n`; continue; } if (f.name === "created_at") { s += `  createdAt      DateTime   @default(now()) @map("created_at")\n`; continue; } if (f.name === "updated_at") { s += `  updatedAt      DateTime   @updatedAt @map("updated_at")\n`; continue; } const pt = pType[f.type] || "String"; const nl = f.nullable ? "?" : ""; if (f.isForeign) { const rel = relations.find(r => r.from === t.name && r.fromField === f.name); if (rel) { s += `  ${f.name.padEnd(14)}${(pt + nl).padEnd(10)}\n  ${toCamel(rel.to).padEnd(14)}${toPascal(rel.to).padEnd(10)}@relation(fields: [${f.name}], references: [${rel.toField}])\n`; continue; } } s += `  ${f.name.padEnd(14)}${pt + nl}\n`; } relations.filter(r => r.to === t.name).forEach(rr => { s += `  ${(toCamel(rr.from) + "s").padEnd(14)}${toPascal(rr.from)}[]\n`; }); s += `\n  @@map("${t.name}")\n}\n\n`; } return s; }
    return "";
  };
  const output = generate(); const exts = { mysql: "schema.sql", postgres: "schema_pg.sql", laravel: "migration.php", prisma: "schema.prisma" }; const colors = { mysql: "#a5f3fc", postgres: "#38bdf8", laravel: "#fb923c", prisma: "#a78bfa" };
  return (
    <ModalShell title="⬇ Export Schema" onClose={onClose} width={740}>
      <div style={{ display: "flex", borderBottom: "1px solid rgba(255,255,255,.06)" }}>
        {tabs.map(t => <button key={t.key} onClick={() => setTab(t.key)} style={{ padding: "10px 16px", background: tab === t.key ? "rgba(52,211,153,.08)" : "transparent", border: "none", borderBottom: tab === t.key ? "2px solid #34d399" : "2px solid transparent", color: tab === t.key ? "#34d399" : "#64748b", cursor: "pointer", fontFamily: "'JetBrains Mono'", fontSize: 12, fontWeight: 500, display: "flex", alignItems: "center", gap: 6 }}><span>{t.icon}</span>{t.label}</button>)}
      </div>
      <pre style={{ padding: 20, margin: 0, maxHeight: 420, overflowY: "auto", fontFamily: "'JetBrains Mono'", fontSize: 11.5, lineHeight: 1.7, color: colors[tab], background: "#080c18" }}>{output}</pre>
      <div style={{ padding: "12px 20px", borderTop: "1px solid rgba(255,255,255,.06)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span style={{ fontSize: 11, color: "#475569", fontFamily: "'JetBrains Mono'" }}>{output.split("\n").length} lines · {exts[tab]}</span>
        <div style={{ display: "flex", gap: 8 }}>
          <Btn variant="cyan" onClick={() => navigator.clipboard?.writeText(output)}>📋 Copy</Btn>
          <Btn variant="amber" onClick={() => { const b = new Blob([output], { type: "text/plain" }); const u = URL.createObjectURL(b); const a = document.createElement("a"); a.href = u; a.download = exts[tab]; a.click(); URL.revokeObjectURL(u); }}>↓ Download</Btn>
        </div>
      </div>
    </ModalShell>
  );
}

export default ExportModal;
